name: magdsoft_flutter_structure
description: magdsoft mobile application structure for flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.2
  fluttertoast: ^8.0.9
  sizer: ^2.0.15
  flutter_svg_provider: ^1.0.3
  pin_code_fields: ^8.0.1
  font_awesome_flutter: ^10.4.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

